### ISSUE TITLE
equation missing  a minus in calcualting hessian?

### ISSUE THREAD

**Issue by narutojxl** [koide3/ndt_omp#12]
Hi, @koide3 , thanks for your sharing work. 
In computeAngleDerivatives() func,  these lines maybe seems miss a minus.
> // h_ang_c2_ << (-sx * cz - cx * sy * sz), (sx * sz - cx * sy * cz), 0;
>    h_ang_c2_ << (-sx * cz - cx * sy * sz), (-sx * sz - cx * sy * cz), 0;

> // h_ang_d1_ << (-cy * cz), (cy * sz), (sy);
>    h_ang_d1_ << (-cy * cz), (cy * sz), (-sy);

>//  h_ang.row(4).noalias() = Eigen::Vector4f((-sx * cz - cx * sy * sz), (sx * sz - cx * sy * cz), 0, 0.0f);
>   h_ang.row(4).noalias() = Eigen::Vector4f((-sx * cz - cx * sy * sz), (-sx * sz - cx * sy * cz), 0, 0.0f);

>// h_ang.row(6).noalias() = Eigen::Vector4f((-cy * cz), (cy * sz), (sy), 0.0f);
>   h_ang.row(6).noalias() = Eigen::Vector4f((-cy * cz), (cy * sz), (-sy), 0.0f);

Best  jxl

**Comment by koide3** [comment]
Hi @narutojxl ,

I'm not sure if it's wrong. Basically, I copied these equations from the original implementation in PCL, and we don't see the minus in the original one.

https://github.com/PointCloudLibrary/pcl/blob/94d05c1066c394dcc2480918b50fde460d74c0d6/registration/include/pcl/registration/impl/ndt.hpp#L292
https://github.com/PointCloudLibrary/pcl/blob/94d05c1066c394dcc2480918b50fde460d74c0d6/registration/include/pcl/registration/impl/ndt.hpp#L295

But, I sometimes doubt if the PCL implementation is correct since it suffers from a strange drift error, and I suppose these euqations could be the cause of the problem. Could you please tell me the document which you referred to find the missing minus so that I can check if they are correct?

**Comment by koide3** [comment]
I took a look at [this](http://www.diva-portal.org/smash/get/diva2:276162/FULLTEXT02.pdf), and it seems the minus is necessary. Did you see an improvement (in terms of accuracy and convergence) when you put minus in these equations?

**Comment by narutojxl** [comment]
Hi @koide3, when i change the sign of calcualting hessian and set `interval_converged = false` [(link is here)](https://github.com/koide3/ndt_omp/issues/13), In the test samples, the accuary did not change, only the convergence is change. PCL native NDT converge is also changing(`400.29, 402.425, 403.319, 406.134`), even though the two factors do not  influence it, maybe we need more big test samples. The following are some comparison pictures.  + or - represents when calculating H use + or -, true or false represents interval_converged is  true or false.
![-VS+](https://user-images.githubusercontent.com/6205343/63407404-fdf0f200-c41e-11e9-8e0f-669720dae65c.png)
![false_VS_true](https://user-images.githubusercontent.com/6205343/63407476-31338100-c41f-11e9-94d2-d8ce105e6d6c.png)

Best 
jxl

**Comment by koide3** [comment]
Hi @narutojxl ,
It looks the convergence change is not very significant. I guess the hessian error might not affect the result so much since the line search in the optimization ensures to decrease the cost function (even if the hessian is wrong). I'll do some tests in the next week to see if it affects the result in some cases...

**Comment by narutojxl** [comment]
@koide3, thank you  very much  in advance!

**Comment by koide3** [comment]
@narutojxl ,
To see if the lack of minus and the convergence flag affect the scan matching result, I conducted some tests under several settings. But, I didn't see any significant difference in both the accuracy and the convergence... I suppose they don't have a big impact on the scan matching result, and leave them as they are.
There can be more errors in the PCL NDT implementation.  In case you see any other errors, please let me know.

**Comment by koide3** [comment]
I did some numerical hessian calculations and confirmed that the PCL implementation is correct (so it was a typo in the original thesis).
Regarding computeStepLengthMT(), when we set a smaller value to transformation epsilon (e.g., 1e-3), "internal_converge" becomes false and the step length computation is performed properly. (I think the default transformation_epsilon = 0.1 is too large...)
So, the pose optimization in the PCL implementation is apparently correct.
